package polimi.ingsoft.server.socket.protocol;

public enum MessageCodes {
    CONNECT,
    MATCHES_LIST_REQUEST,
    MATCHES_LIST_UPDATE,
    MATCH_JOIN_REQUEST,
    MATCH_JOIN_UPDATE,
    MATCH_CREATE_REQUEST,
    MATCH_CREATE_UPDATE,
    LOBBY_INFORMATION_REQUEST,
    LOBBY_INFORMATION_UPDATE,
    LOBBY_PLAYER_JOINED_UPDATE,
    LOBBY_PLAYER_LEFT_UPDATE;
}
