package polimi.ingsoft.server.socket.protocol;

public enum MessageCodes {
    // Game setup and lobby
    CONNECT,
    SET_NICKNAME_REQUEST,
    SET_NICKNAME_UPDATE,
    MATCHES_LIST_REQUEST,
    MATCHES_LIST_UPDATE,
    MATCH_JOIN_REQUEST,
    MATCH_JOIN_UPDATE,
    MATCH_CREATE_REQUEST,
    MATCH_CREATE_UPDATE,
    LOBBY_PLAYERS_UPDATE,
    MATCH_CONTROLLER_STUB_UPDATE,

    // Game initialization
    SET_COLOR_REQUEST,
    SET_INITIAL_CARD_REQUEST,
    SET_QUEST_CARD_REQUEST,
    SET_INITIAL_SETTINGS_UPDATE,

    // Game
    MATCH_GAME_STATE_UPDATE,
    MATCH_PUBLIC_BOARD_UPDATE,
    MATCH_BOARD_UPDATE,
    MATCH_PLAYER_HAND_UPDATE,
    MATCH_SEND_BROADCAST_MESSAGE_REQUEST,
    MATCH_BROADCAST_MESSAGE_UPDATE,
    MATCH_SEND_PRIVATE_MESSAGE_REQUEST,
    MATCH_PRIVATE_MESSAGE_UPDATE,
    MATCH_DRAW_REQUEST,
    MATCH_PLACE_REQUEST,
    ERROR
}
