package polimi.ingsoft.server.socket.protocol;

public enum MessageCodes {
    CONNECT,
    SET_NICKNAME_REQUEST,
    SET_NICKNAME_UPDATE,
    SET_COLOR_REQUEST,
    SET_COLOR_UPDATE,
    SET_INITIAL_REQUEST,
    SET_INITIAL_UPDATE,
    SET_QUEST_REQUEST,
    SET_QUEST_UPDATE,
    MATCHES_LIST_REQUEST,
    MATCHES_LIST_UPDATE,
    MATCH_JOIN_REQUEST,
    MATCH_JOIN_UPDATE,
    MATCH_CREATE_REQUEST,
    MATCH_CREATE_UPDATE,
    LOBBY_INFORMATION_REQUEST,
    LOBBY_INFORMATION_UPDATE,
    LOBBY_PLAYER_JOINED_UPDATE,
    LOBBY_PLAYER_LEFT_UPDATE,
    MATCH_SEND_MESSAGE_REQUEST,
    MATCH_SEND_PRIVATE_MESSAGE_REQUEST,
    MATCH_DRAW_REQUEST,
    MATCH_PLACE_REQUEST;
}
